language: python
python:
  - "3.8"
# command to install dependencies
os:
  - linux

install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run  -m pytest tests/

after_success:
  - coveralls
